### ISSUE TITLE
组件注册示例→父组件和子组件 的demo写错了

### ISSUE THREAD

**Issue by linzb93** [keepfool/vue-tutorials#1]
系统报错，而且你在博客园里也表明这种写法是错的。

**Comment by keepfool** [comment]
这个例子可能让你误解了，我故意放了一个错误的示例在这儿的。
晚上回家后，我把这个调整过来吧，免得有其他人也误解了。

我在父组件的template中是用了`<child-component></child-component>`的
`template :'<p>This is a Parent component!</p><child-component></child-component>'`
