### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by ibbatta** [keepfool/vue-tutorials#13]
It's possible have an english translation of this?
Seems very interesting

**Comment by keepfool** [comment]
This tutorial is writing on vue 1.x, the examples may not work in vue 2.x.
There are many differences between vue 1.x and vue 2.x.
It's time to enjoy vue 2.x.

If you want some English tutorial, I suggest [https://coligo.io/tag/vue](https://coligo.io/tag/vue) or [https://laracasts.com/search?q=vue](https://laracasts.com/search?q=vue)
