### ISSUE TITLE
V-show后面紧跟V-else这种写法不支持了吗？vue.js564行报错。

### ISSUE THREAD

**Issue by wangmaojiawan** [keepfool/vue-tutorials#19]
v-else used on element <h1> without corresponding v-if.

**Comment by HeZhaoyin** [comment]
怎么github自动发邮件给我了....
刚查了下文档.. 是的.. 2.0开始不支持这种写法
“v-else 不能再跟在 v-show后面使用。请在v-if的否定分支中使用v-show来替代”
详见：http://cn.vuejs.org/v2/guide/migration.html#v-show后面使用v-else-移除

**Comment by wangmaojiawan** [comment]
多谢，我是初学者，跟着Vue.js——60分钟快速入门例子在看对应的指令，看来这个文档没有更新啊。

**Comment by HeZhaoyin** [comment]
@wangmaojiawan 客气了，其实我也是初学者.. 网上好多教程都是Vue 1.x版本的- -，无奈Vue2.0的改动又太大了... 所以导致好多教程因为版本不同而有一些坑.. 结合Vue的官方文档来看就好了，文档写得真是非常详细... 就是好多都看不懂..边看边练吧
