### ISSUE TITLE
我看你的弹窗组件有点疑问

### ISSUE THREAD

**Issue by dolphin0618** [keepfool/vue-tutorials#2]
我是vue初学者，我按你的例子做了个弹窗组件。现在有个问题。我有个页面需要两个弹窗，一个弹电话号，一个弹2维码。我在页面上引了两个模板，导致show为true的时候两个弹窗都会出现，这种怎么解决。

**Comment by keepfool** [comment]
1. 为弹框组件设置`props: ['show']`
2. Vue实例的data选项设置两个属性，比如：

```
data: {
showPhone: false,
showCode: false
}
```

3.在画面上创建两个对话框
例如：

```
<modal-dialog :show="showPhone"></modal-dialog>
<modal-dialog :show="showCode"></modal-dialog>
```

4.一些按钮事件更改showPhone或者showCode...

**Comment by dolphin0618** [comment]
试了一下，可以了。
但是我不明白设置`props: ['show']`后
为什么
```
data: {
showPhone: false,
showCode: false
}
```
这样写也可以传递给show，有什么规则么?我在官方教程没有看到这一点

**Comment by dolphin0618** [comment]
ok, 明白了。谢谢

**Comment by keepfool** [comment]
@dolphin0618 不用谢，大家多交流。
