### ISSUE TITLE
父组件和子组件

### ISSUE THREAD

**Issue by Anderson-James-oss** [keepfool/vue-tutorials#22]
###  我用的**Vue2.0**得Js学习的

> 教程中父组件里面template属性定义组件需要的HTML那样写会报错，提示需要一个根元素

![image](https://user-images.githubusercontent.com/28972785/27312883-98ebec08-559d-11e7-82c6-c36623e46e41.png)

* **result**

![image](https://user-images.githubusercontent.com/28972785/27312844-6c12b658-559d-11e7-8d50-85073af5b3f2.png)

> 在template属性定义组件需要的HTML加上一个根元素就对了

![image](https://user-images.githubusercontent.com/28972785/27312762-fe199fcc-559c-11e7-8391-96e10faa33fa.png)

* **result**

![image](https://user-images.githubusercontent.com/28972785/27312956-ece8d3ca-559d-11e7-96ff-e0e0edc99ae6.png)

> 在使用的时候，如果将子组件注册的标签写在父组件里面，也没有报错

![image](https://user-images.githubusercontent.com/28972785/27313000-31a4e378-559e-11e7-9335-7148426fc316.png)

* **result**

![image](https://user-images.githubusercontent.com/28972785/27313015-4228bfee-559e-11e7-83c2-1272a58797e1.png)

**Comment by keepfool** [comment]
在vue2中提倡为每个组件指定一个根元素。此外，vue2的验证机制比vue1更加严格
