### ISSUE TITLE
留言表示感谢+1

### ISSUE THREAD

**Issue by huoshan12345** [keepfool/vue-tutorials#4]
十分十分感谢作者的教程，作者实在太用心，教程超级详细。
我刚学完vue-resource，作者还十分贴心的提供了在线的api，简直良心。不过我个人还是自己用asp.net core搭了一个，顺便也摸索了一下新的web api（和以前的有一些不同）
总之，十分感谢了:+1:

**Comment by keepfool** [comment]
客气~
