### ISSUE TITLE
小白求指教，先表示感谢！

### ISSUE THREAD

**Issue by zhizunbao84** [keepfool/vue-tutorials#6]
关于Vue.js——60分钟组件快速入门（下篇）的两个小疑惑：
1、在这篇里面最后增删查改那个例子里面，你调用内置的ready()函数获取主键列，你这个只是为了演示用法吧，其实不用也可以吧？
2、弹出修改数据的对话框时，为什么要使用对象的深拷贝呢？

**Comment by keepfool** [comment]
1. 这个只是为了演示，不用当然可以哦。
2. 用深拷贝是为了不直接修改原对象。
   举个例子：一个对象 { userName: 'Alex', age: 28 }，你直接用一个变量接收它，得到的是其引用类型；在页面上通过表单修改其内容时，由于vue是双向绑定的，会直接影响到列表中的数据。
